name: Publish to GithubPackages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Get the tag version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Publish to GitHub Packages Apache Maven
        env:
          GITHUB_PACKAGE_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_PACKAGE_TOKEN: ${{ secrets.TOKEN }}
          GRADLE_PUBLISH_VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: ./gradlew assembleRelease publish