name: Publish to Github Packages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Get the tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: Publish to GitHub Packages
        env:
          GITHUB_PACKAGE_USERNAME: phamvanducdev  # ${{ secrets.NPM_USERNAME }}
          GITHUB_PACKAGE_TOKEN: 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 # ${{ secrets.NPM_TOKEN }}
          GRADLE_PUBLISH_VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: ./gradlew assembleRelease publish